# Datei im Anhängemodus öffnen (wird erstellt, wenn sie nicht existiert)
with open('config.json', 'a') as file:
    ip_adress = input("Wie ist die IP Adresse des Raspberry Servers?")
    file.write('{\n')
    file.write('   "Site" : {\n')
    file.write('        "server"    : "')
    file.write(ip_adress)
    file.write('",\n')
    file.write('        "port"      : "7777"\n')
    file.write('    },\n')
    file.write('    "Websocket" : {\n')
    file.write('    "server"    : "')
    file.write(ip_adress)
    file.write('",\n')
    file.write('        "port"      :"7778"\n')
    file.write('        }\n')
    file.write('\n')
    file.write('}')